"""
Question :- 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        l1=[]
        l2=[]
        for i in s:
            l1.append(i)
        for j in t:
            l2.append(j)
        
        l1.sort()
        l2.sort()
        for k in range(len(l1)):
            if(l1[k]!=l2[k]):
                return l2[k]
        return l2[len(l2)-1]
